name: flutter_ffmpeg_media_editor
description: "A powerful Flutter package for advanced media editing using FFmpeg. Features include text overlays, emoji/sticker placement, color filters, video speed control, image rotation, and more. Perfect for creating social media content, video editing apps, and multimedia applications."
version: 1.0.0
homepage: https://github.com/ElshiatyTube/flutter-ffmpeg-fullyfunctional-media-editor


# Add repository information
repository: https://github.com/ElshiatyTube/flutter-ffmpeg-fullyfunctional-media-editor

# Add issue tracker
issue_tracker: https://github.com/ElshiatyTube/flutter-ffmpeg-fullyfunctional-media-editor/issues

keywords:
  - flutter
  - ffmpeg
  - media
  - video
  - image
  - editing
  - text-overlay
  - emoji
  - sticker
  - filter
  - speed
  - rotation
  - crop
  - audio
  - gif
  - thumbnail
  - social-media
  - multimedia

topics:
  - media
  - video
  - image
  - editing
  - ffmpeg

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.10.0
  ffmpeg_kit_flutter_new: ^2.0.0
  camera: ^0.11.1
  file_picker: ^10.2.0
  audioplayers: 6.5.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  image: ^4.5.4
  image_cropper: ^9.1.0
  gallery_saver_plus: ^3.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see
# the following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
